### ISSUE TITLE
inputs must be a list of at least one Tensor with the same dtype and shape

### ISSUE THREAD

**Issue by Lugangz** [tomMoral/AdaptiveOptim#2]
It's a great job!!! When I run the cmd, python NIPS_figures.py --data artificial --save_dir layer1, an error happened like below, I wonder how to solve.

Traceback (most recent call last):
  File "/AdaptiveOptim/NIPS_figures.py", line 249, in <module>
    network = LinearNetwork(D, 1, gpu_usage=gpu_usage, exp_dir=NAME_EXP)
  File "\AdaptiveOptim\adaopt\linear_network.py", line 28, in __init__
    super().__init__(n_layers=n_layers, name=name, **kwargs)
  File "\AdaptiveOptim\adaopt\_loptim_network.py", line 22, in __init__
    self._construct()
  File "\AdaptiveOptim\adaopt\_loptim_network.py", line 77, in _construct
    self._train = self._mk_training_step()
  File "\AdaptiveOptim\adaopt\linear_network.py", line 153, in _mk_training_step
    _reg = tf.add_n(tf.get_collection("regularisation"))
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2222, in add_n
    raise ValueError("inputs must be a list of at least one Tensor with the "
ValueError: inputs must be a list of at least one Tensor with the same dtype and shape

**Comment by scut-salmon** [comment]
same question. any update?

**Comment by scut-salmon** [comment]
There's Spelling mistake in _reg = tf.add_n(tf.get_collection("regularisation"))
and it should be 
_reg = tf.add_n(tf.get_collection("regularization"))

**Comment by fengluyukaixin** [comment]
I met an error happened like below, I wonder how to solve.
'FactoNetwork' object has no attribute 'global_step',
thank you very much.
